[versions]
agp = "8.5.1"
kotlin = "1.9.24"
coreKtx = "1.13.1"
junit = "4.13.2"
jsonunit = "3.4.1"
appcompat = "1.7.0"
material = "1.12.0"
moshi = "1.15.1"
okhttp = "4.12.0"
assertj = "3.26.3"
lifecycleProcess = "2.8.4"
kotlinxCoroutinesTest = "1.8.1"
activityCompose = "1.9.1"
runtimeLivedata = "1.6.8"
material3 = "1.2.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockito = { group = "org.mockito", name = "mockito-core", version = "5.14.1" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
moshi-kotlin = { group = "com.squareup.moshi", name="moshi-kotlin", version.ref = "moshi" }
moshi-adapters = { group = "com.squareup.moshi", name="moshi-adapters", version.ref = "moshi" }
robolectric-test = { group = "org.robolectric", name = "robolectric", version = "4.13" }
awaitility = { group = "org.awaitility", name = "awaitility", version = "4.3.0" }

okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-mockserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
jsonunit = { group = "net.javacrumbs.json-unit", name = "json-unit-assertj", version.ref = "jsonunit" }

## sample app
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3"  }
androidx-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtimeLivedata" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
